name: gem_ore_struct_finder_mc
description: Gem, Ore & Struct Finder for MC - Discover diamonds, gold, netherite, villages, strongholds and more using world seed analysis. Features biome filtering, coordinate search, and probability-based results for optimal mining efficiency.
publish_to: 'none'
version: 1.0.0+1

# SEO and App Store metadata
homepage: https://github.com/Lock128/gem-ore-struct-finder-mc
repository: https://github.com/Lock128/gem-ore-struct-finder-mc
issue_tracker: https://github.com/Lock128/gem-ore-struct-finder-mc/issues
documentation: https://github.com/Lock128/gem-ore-struct-finder-mc/wiki

# App metadata for stores
metadata:
  keywords: 
    - ore finder
    - diamond finder
    - seed analysis
    - mining tool
    - netherite finder
    - structure finder
    - biome filter
    - world generation
    - gaming utility
    - block game

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  screenshot: ^3.0.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true