name: minecraft_finder
description: Advanced Minecraft Ore & Structure Finder - Discover diamonds, gold, netherite, villages, strongholds and more using world seed analysis. Features biome filtering, coordinate search, and probability-based results for optimal mining efficiency.
publish_to: 'none'
version: 1.0.0+1

# SEO and App Store metadata
homepage: https://github.com/Lock128/minecraft-finder
repository: https://github.com/Lock128/minecraft-finder
issue_tracker: https://github.com/Lock128/minecraft-finder/issues
documentation: https://github.com/Lock128/minecraft-finder/wiki

# App metadata for stores
metadata:
  keywords: 
    - minecraft
    - ore finder
    - diamond finder
    - seed analysis
    - mining tool
    - netherite finder
    - structure finder
    - biome filter
    - world generation
    - gaming utility

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  screenshot: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true